// Code generated by MockGen. DO NOT EDIT.
// Source: asset.go

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"
	models "server/internal/models"

	gomock "github.com/golang/mock/gomock"
)

// MockIAssetService is a mock of IAssetService interface.
type MockIAssetService struct {
	ctrl     *gomock.Controller
	recorder *MockIAssetServiceMockRecorder
}

// MockIAssetServiceMockRecorder is the mock recorder for MockIAssetService.
type MockIAssetServiceMockRecorder struct {
	mock *MockIAssetService
}

// NewMockIAssetService creates a new mock instance.
func NewMockIAssetService(ctrl *gomock.Controller) *MockIAssetService {
	mock := &MockIAssetService{ctrl: ctrl}
	mock.recorder = &MockIAssetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssetService) EXPECT() *MockIAssetServiceMockRecorder {
	return m.recorder
}

// CreateAsset mocks base method.
func (m *MockIAssetService) CreateAsset(asset *models.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsset", asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAsset indicates an expected call of CreateAsset.
func (mr *MockIAssetServiceMockRecorder) CreateAsset(asset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsset", reflect.TypeOf((*MockIAssetService)(nil).CreateAsset), asset)
}

// DeleteAsset mocks base method.
func (m *MockIAssetService) DeleteAsset(id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsset", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAsset indicates an expected call of DeleteAsset.
func (mr *MockIAssetServiceMockRecorder) DeleteAsset(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsset", reflect.TypeOf((*MockIAssetService)(nil).DeleteAsset), id)
}

// GetAssetById mocks base method.
func (m *MockIAssetService) GetAssetById(id uint32) (*models.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetById", id)
	ret0, _ := ret[0].(*models.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetById indicates an expected call of GetAssetById.
func (mr *MockIAssetServiceMockRecorder) GetAssetById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetById", reflect.TypeOf((*MockIAssetService)(nil).GetAssetById), id)
}

// GetAssetsByDepartmentId mocks base method.
func (m *MockIAssetService) GetAssetsByDepartmentId(id uint32) ([]*models.Asset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetsByDepartmentId", id)
	ret0, _ := ret[0].([]*models.Asset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetsByDepartmentId indicates an expected call of GetAssetsByDepartmentId.
func (mr *MockIAssetServiceMockRecorder) GetAssetsByDepartmentId(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetsByDepartmentId", reflect.TypeOf((*MockIAssetService)(nil).GetAssetsByDepartmentId), id)
}

// UpdateAsset mocks base method.
func (m *MockIAssetService) UpdateAsset(id uint32, asset *models.Asset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsset", id, asset)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAsset indicates an expected call of UpdateAsset.
func (mr *MockIAssetServiceMockRecorder) UpdateAsset(id, asset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsset", reflect.TypeOf((*MockIAssetService)(nil).UpdateAsset), id, asset)
}
