version: "3.2"

services:
  mysql_db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: pwd
    ports:
      - 3306:3306
    volumes:
      - mysql_db1:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 10
  server:
    depends_on:
      mysql_db:
        condition: service_healthy
    container_name: server
    environment:
      DB_USER: root
      DB_PASSWORD: pwd
      DB_HOST: host.docker.internal
      DB_NAME: db
    ports:
      - 8080:8080
    build: ./server

volumes:
  mysql_db1:
    driver: local