version: "3.2"

services:
  db:
    image: mysql
    container_name: db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3306:3306
    volumes:
      - mysql_db1:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 10
  server:
    depends_on:
      db:
        condition: service_healthy
    build: ./server
    container_name: server
    env_file: .env
    ports:
      # machinePort:appPort
      - 8080:8080

volumes:
  mysql_db1:
    driver: local