version: "3.2"

services:
  mysql_db:
    image: mysql
    container_name: db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3306:3306
    volumes:
      - mysql_db1:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 10
  server:
    depends_on:
      mysql_db:
        condition: service_healthy
    container_name: server
    env_file: .env
    environment:
      - CONNECTION_URL=$CONNECTION_URL
      - PORT=$SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    build: ./server

volumes:
  mysql_db1:
    driver: local