version: "3.2"

services:
  mysql_db:
    image: mysql
    container_name: db
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql_db1:/var/lib/mysql
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 10s
          retries: 10
  server:
    depends_on:
      mysql_db:
        condition: service_healthy
    container_name: server
    env_file: .env
    ports:
      - 8080:8080
    build: ./server

volumes:
  mysql_db1:
    driver: local