name: Deploy staging

on:
  push:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Can be found as part of the Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }}
