name: Deploy staging

on:
  push:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    needs: [unittest]
    steps:
      - name: Trigger deployment
        uses: johnbeynon/render-deploy-action@v1
        with: 
          service-id: ${{ secrets.RENDER_SERVICE_ID }}}
          api-key: ${{ secrets.RENDER_API_KEY }}